version: '3'
services:
  room-assistant:
    build: .
    network_mode: host
    environment:
      NODE_CONFIG: >
        {
          "global": {
            "instanceName": "dev-instance",
            "integrations": []
          }
        }
