global:
  instanceName: test-instance
  integrations:
    - bluetoothLowEnergy
gpio:
  binarySensors:
    - name: PIR Sensor
      pin: 23
    - name: Radar
      pin: 24
      deviceClass: motion
shell:
  sensors:
    - name: Simple Test
      command: echo test
      cron: '* * * * *'
    - name: Regex Test
      command: echo 'test 123'
      cron: '* * * * */2'
      regex: '[1-9]+'
      deviceClass: 'timestamp'
      icon: 'mdi:test'
      unitOfMeasurement: 'tests'
  switches:
    - name: Test Switch
      onCommand: echo on
      offCommand: echo off
